name: Send Daily Dynatrace Report

on:
  schedule:
    - cron: '35 18 * * *'  # runs daily at 12:05 AM IST
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download previous workbook
        uses: actions/download-artifact@v4
        with:
          name: dynatrace-workbook
          path: .

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas openpyxl requests

      - name: Run dynatrace report
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          LOGINCONTROLLER_URL: ${{ secrets.LOGINCONTROLLER_URL }}
          MOTORINSURANCE_URL: ${{ secrets.MOTORINSURANCE_URL }}
        run: python test.py

      - name: Upload updated workbook
        uses: actions/upload-artifact@v4
        with:
          name: dynatrace-workbook
          path: dynatrace_metrics.xlsx
